# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_auto_20171010_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField(verbose_name='from')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='to')),
                ('project_backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_project', to='project.ProjectBacklog')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sprint',
            unique_together=set([('name', 'project_backlog')]),
        ),
    ]
