# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productbacklog_product_owner', to='auth.Group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('product_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productbacklog_product_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
