# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
