# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_completed',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
    ]
