# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 14:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('presentage_complete', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='%completed')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='log at')),
                ('update', models.DateTimeField(auto_now=True)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todolog', to='todo.Todo')),
            ],
        ),
    ]
