# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 15:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='presentage_complete',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='%completed'),
        ),
        migrations.AlterField(
            model_name='todolog',
            name='presentage_complete',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='%completed'),
        ),
    ]
