# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 20:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('project', '0002_auto_20171010_2307'),
        ('accounts', '0001_initial'),
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('is_sub_task', models.BooleanField(default=False)),
                ('task_completed', models.BooleanField(default=False)),
                ('link_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='task.Task')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='task.Task')),
                ('projectBacklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksInBacklogs', to='project.ProjectBacklog')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='groups.Group', verbose_name='scrum')),
            ],
        ),
        migrations.CreateModel(
            name='TaskProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignTo', to='accounts.User')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskSprint', to='sprint.Sprint')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taskProperty', to='task.Task')),
            ],
        ),
    ]
