# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 15:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covey', '0001_initial'),
        ('sprint', '0001_initial'),
        ('project', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('is_sub_task', models.BooleanField(default=False)),
                ('presentage_complete', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='%completed')),
                ('task_completed', models.BooleanField(default=False)),
                ('estimated_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('acutal_time', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('link_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='task.Task')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='task.Task')),
                ('projectBacklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksInBacklogs', to='project.ProjectBacklog')),
                ('task_type', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='taskcovmat', to='covey.CoveyMatrix')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='groups.Group', verbose_name='Team')),
            ],
            options={
                'ordering': ('task_completed', 'task_type', 'priority'),
            },
        ),
        migrations.CreateModel(
            name='TaskProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignTo', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskSprint', to='sprint.Sprint')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taskProperty', to='task.Task')),
                ('task_stage', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='taskStage', to='project.TaskStages')),
            ],
        ),
    ]
