# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('task_completed', 'task_type', '-priority')},
        ),
    ]
