# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 13:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='acutal_time',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
