# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20171012_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='groups.Group', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='taskproperty',
            name='assign_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignTo', to=settings.AUTH_USER_MODEL),
        ),
    ]
