# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20171008_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskproperty',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
