# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='taskcovmat', to='covey.CoveyMatrix'),
        ),
    ]
