# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20171024_0032'),
        ('task', '0006_task_presentage_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskproperty',
            name='task_stage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='taskStage', to='project.ProjeckBacklogStages'),
        ),
    ]
