# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 12:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjeckBacklogStages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('stage',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETA', models.DateField()),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='start date')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projectBacklog', to='project.Project')),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectBacklogOwner', to=settings.AUTH_USER_MODEL)),
                ('scrum_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectBacklogSM', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBacklogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_length', models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sprint length')),
                ('sprint_template', models.CharField(blank=True, default='sprint_', max_length=15)),
                ('project_backlog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projectBacklogSetting', to='project.ProjectBacklog')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='stage id')),
                ('stage_name', models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='stage name')),
            ],
            options={
                'ordering': ('stage',),
            },
        ),
        migrations.AddField(
            model_name='projeckbacklogstages',
            name='project_backlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stagestoProjectBacklog', to='project.ProjectBacklogSettings'),
        ),
        migrations.AddField(
            model_name='projeckbacklogstages',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stagestoTaskStages', to='project.TaskStages'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'company')]),
        ),
        migrations.AlterUniqueTogether(
            name='projeckbacklogstages',
            unique_together=set([('project_backlog', 'stage')]),
        ),
    ]
