# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 14:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETA', models.DateField()),
                ('development_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectBacklog', to='groups.Group')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projectBacklog', to='project.Project')),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectBacklogOwner', to='accounts.User')),
                ('scrum_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectBacklogSM', to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBacklogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_length', models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sprint length')),
                ('project_backlog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projectBacklogSetting', to='project.ProjectBacklog')),
            ],
        ),
    ]
