# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbacklog',
            name='project_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectBacklogOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbacklog',
            name='scrum_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectBacklogSM', to=settings.AUTH_USER_MODEL),
        ),
    ]
