# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbacklog',
            name='development_team',
        ),
    ]
