# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstages',
            options={'ordering': ('pk',)},
        ),
    ]
