# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbacklogsettings',
            name='project_start_date',
            field=models.DateField(default=datetime.date(2017, 11, 3), verbose_name='start date'),
        ),
    ]
