# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 21:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20171010_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjeckBacklogStages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stagestoProjectBacklog', to='project.ProjectBacklogSettings')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='stage id')),
                ('stage_name', models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='stage name')),
            ],
            options={
                'ordering': ('stage',),
            },
        ),
        migrations.AddField(
            model_name='projeckbacklogstages',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stagestoTaskStages', to='project.TaskStages'),
        ),
        migrations.AlterUniqueTogether(
            name='projeckbacklogstages',
            unique_together=set([('project_backlog', 'stage')]),
        ),
    ]
