# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectbacklogsettings_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbacklogsettings',
            name='project_start_date',
        ),
        migrations.AddField(
            model_name='projectbacklog',
            name='project_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
    ]
