# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20171103_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectbacklog',
            old_name='project_start_date',
            new_name='start_date',
        ),
    ]
