# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('name',)]),
        ),
    ]
