# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 12:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprint', '__first__'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2017, 11, 16))),
                ('log', models.TextField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingSprint', to='sprint.Sprint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammeeting', to='groups.Group')),
            ],
            options={
                'ordering': ['-date', 'type'],
            },
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Meeting type')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='meetingtype',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingtyperel', to='meeting.MeetingType'),
        ),
    ]
