# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('log', models.TextField()),
                ('tasks_meta', models.CharField(default='', max_length=200, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammeeting', to='groups.Group')),
            ],
            options={
                'ordering': ['-update'],
            },
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Meeting type')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='meetingtype',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingtyperel', to='meeting.MeetingType'),
        ),
    ]
