# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20171116_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='sprint',
        ),
    ]
