# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_remove_meeting_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='sprints',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
