# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_meeting_sprints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='sprints',
            new_name='tasks_meta',
        ),
    ]
