# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lite_scrum', '0002_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='product_backlog',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='backlog',
            name='product_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_product_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backlog',
            name='release_backlog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backlog',
            name='scrum_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_scrum_master', to=settings.AUTH_USER_MODEL),
        ),
    ]
